### ISSUE TITLE
Plugin installed failed on Redmine 2.3.1

### ISSUE THREAD

**Issue by doublechiang** [hipchat/redmine_hipchat#17]
Hi,

Sine I has some problem when installed on Redmine 1.4.2, so I upgradeed to 2.3.1.
The new installed Redmine seems work fine, the plugin can be displayed, configured.
But After configured, when try to send to hipchat, it will has some error.

See below, any idea will be appreciated.
----------------- cut here ----------------
NoMethodError (undefined method `hipchat_auth_token' for #<Project:0x7fcca468e8b8>):
  lib/redmine/hook.rb:61:in`send'
  lib/redmine/hook.rb:61:in `call_hook'
  lib/redmine/hook.rb:61:in`each'
  lib/redmine/hook.rb:61:in `call_hook'
  lib/redmine/hook.rb:58:in`tap'
  lib/redmine/hook.rb:58:in `call_hook'
  app/models/issue.rb:992:in`save_issue_with_child_records'
  app/models/issue.rb:977:in `save_issue_with_child_records'
  app/controllers/issues_controller.rb:179:in`update'

**Comment by doublechiang** [comment]
More logs,

When I tried to uninstall it, there are errors.
jyjiang@swdev:/usr/share/redmine/plugins$ sudo rake redmine:plugins:migrate NAME=redmine_hipchat VERSION=0 RAILS_ENV=production --trace(in /usr/share/redmine-2.3-stable)
*\* Invoke redmine:plugins:migrate (first_time)
*\* Invoke environment (first_time)
*\* Execute environment
*\* Execute redmine:plugins:migrate
Migrating redmine_hipchat (HipChat)...
==  AddHipChatTokenAndRoomIdToProject: reverting ==============================
-- remove_column("projects", :hipchat_notify)
rake aborted!
An error has occurred, all later migrations canceled:

Mysql2::Error: Can't DROP 'hipchat_notify'; check that column/key exists: ALTER TABLE `projects` DROP `hipchat_notify`/usr/lib/ruby/gems/1.8/gems/activerecord-3.2.13/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:245:in `query'
/usr/lib/ruby/gems/1.8/gems/activerecord-3.2.13/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:245:in`execute'
/usr/lib/ruby/gems/1.8/gems/activerecord-3.2.13/lib/active_record/connection_adapters/abstract_adapter.rb:280:in `log'
/usr/lib/ruby/gems/1.8/gems/activesupport-3.2.13/lib/active_support/notifications/instrumenter.rb:20:in`instrument'
/usr/lib/ruby/gems/1.8/gems/activerecord-3.2.13/lib/active_record/connection_adapters/abstract_adapter.rb:275:in `log'
/usr/lib/ruby/gems/1.8/gems/activerecord-3.2.13/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:245:in`execute'
/usr/lib/ruby/gems/1.8/gems/activerecord-3.2.13/lib/active_record/connection_adapters/mysql2_adapter.rb:211:in `execute'
/usr/lib/ruby/gems/1.8/gems/activerecord-3.2.13/lib/active_record/connection_adapters/abstract/schema_statements.rb:279:in`remove_column'
/usr/lib/ruby/gems/1.8/gems/activerecord-3.2.13/lib/active_record/connection_adapters/abstract/schema_statements.rb:278:in `each'
/usr/lib/ruby/gems/1.8/gems/activerecord-3.2.13/lib/active_record/connection_adapters/abstract/schema_statements.rb:278:in`remove_column'
/usr/lib/ruby/gems/1.8/gems/activerecord-3.2.13/lib/active_record/migration.rb:466:in `send'
/usr/lib/ruby/gems/1.8/gems/activerecord-3.2.13/lib/active_record/migration.rb:466:in`method_missing'
/usr/lib/ruby/gems/1.8/gems/activerecord-3.2.13/lib/active_record/migration.rb:438:in `say_with_time'
/usr/lib/ruby/1.8/benchmark.rb:293:in`measure'
/usr/lib/ruby/gems/1.8/gems/activerecord-3.2.13/lib/active_record/migration.rb:438:in `say_with_time'
/usr/lib/ruby/gems/1.8/gems/activerecord-3.2.13/lib/active_record/migration.rb:458:in`method_missing'
/usr/lib/ruby/gems/1.8/gems/activerecord-3.2.13/lib/active_record/migration.rb:402:in `send'
/usr/lib/ruby/gems/1.8/gems/activerecord-3.2.13/lib/active_record/migration.rb:402:in`migrate'
/usr/lib/ruby/gems/1.8/gems/activerecord-3.2.13/lib/active_record/migration.rb:401:in `each'
/usr/lib/ruby/gems/1.8/gems/activerecord-3.2.13/lib/active_record/migration.rb:401:in`migrate'
/usr/lib/ruby/gems/1.8/gems/activerecord-3.2.13/lib/active_record/migration.rb:358:in `revert'
/usr/lib/ruby/gems/1.8/gems/activerecord-3.2.13/lib/active_record/migration.rb:400:in`migrate'
/usr/lib/ruby/1.8/benchmark.rb:293:in `measure'
/usr/lib/ruby/gems/1.8/gems/activerecord-3.2.13/lib/active_record/migration.rb:399:in`migrate'
/usr/lib/ruby/gems/1.8/gems/activerecord-3.2.13/lib/active_record/connection_adapters/abstract/connection_pool.rb:129:in `with_connection'
/usr/lib/ruby/gems/1.8/gems/activerecord-3.2.13/lib/active_record/migration.rb:389:in`migrate'
/usr/lib/ruby/gems/1.8/gems/activerecord-3.2.13/lib/active_record/migration.rb:528:in `__send__'
/usr/lib/ruby/gems/1.8/gems/activerecord-3.2.13/lib/active_record/migration.rb:528:in`migrate'
/usr/lib/ruby/gems/1.8/gems/activerecord-3.2.13/lib/active_record/migration.rb:720
/usr/lib/ruby/gems/1.8/gems/activerecord-3.2.13/lib/active_record/migration.rb:777:in `call'
/usr/lib/ruby/gems/1.8/gems/activerecord-3.2.13/lib/active_record/migration.rb:777:in`ddl_transaction'
/usr/lib/ruby/gems/1.8/gems/activerecord-3.2.13/lib/active_record/migration.rb:719:in `migrate'
/usr/lib/ruby/gems/1.8/gems/activerecord-3.2.13/lib/active_record/migration.rb:700:in`each'
/usr/lib/ruby/gems/1.8/gems/activerecord-3.2.13/lib/active_record/migration.rb:700:in `migrate'
/usr/lib/ruby/gems/1.8/gems/activerecord-3.2.13/lib/active_record/migration.rb:574:in`down'
/usr/lib/ruby/gems/1.8/gems/activerecord-3.2.13/lib/active_record/migration.rb:555:in `migrate'
/usr/share/redmine-2.3-stable/lib/redmine/plugin.rb:453:in`migrate_plugin'
/usr/share/redmine-2.3-stable/lib/redmine/plugin.rb:425:in `migrate'
/usr/share/redmine-2.3-stable/lib/redmine/plugin.rb:436:in`migrate'
/usr/share/redmine-2.3-stable/lib/tasks/redmine.rake:74
/usr/lib/ruby/gems/1.8/gems/rake-10.0.4/lib/rake/task.rb:246:in `call'
/usr/lib/ruby/gems/1.8/gems/rake-10.0.4/lib/rake/task.rb:246:in`execute'
/usr/lib/ruby/gems/1.8/gems/rake-10.0.4/lib/rake/task.rb:241:in `each'
/usr/lib/ruby/gems/1.8/gems/rake-10.0.4/lib/rake/task.rb:241:in`execute'
/usr/lib/ruby/gems/1.8/gems/rake-10.0.4/lib/rake/task.rb:184:in `invoke_with_call_chain'
/usr/lib/ruby/1.8/monitor.rb:242:in`synchronize'
/usr/lib/ruby/gems/1.8/gems/rake-10.0.4/lib/rake/task.rb:177:in `invoke_with_call_chain'
/usr/lib/ruby/gems/1.8/gems/rake-10.0.4/lib/rake/task.rb:170:in`invoke'
/usr/lib/ruby/gems/1.8/gems/rake-10.0.4/lib/rake/application.rb:143:in `invoke_task'
/usr/lib/ruby/gems/1.8/gems/rake-10.0.4/lib/rake/application.rb:101:in`top_level'
/usr/lib/ruby/gems/1.8/gems/rake-10.0.4/lib/rake/application.rb:101:in `each'
/usr/lib/ruby/gems/1.8/gems/rake-10.0.4/lib/rake/application.rb:101:in`top_level'
/usr/lib/ruby/gems/1.8/gems/rake-10.0.4/lib/rake/application.rb:110:in `run_with_threads'
/usr/lib/ruby/gems/1.8/gems/rake-10.0.4/lib/rake/application.rb:95:in`top_level'
/usr/lib/ruby/gems/1.8/gems/rake-10.0.4/lib/rake/application.rb:73:in `run'
/usr/lib/ruby/gems/1.8/gems/rake-10.0.4/lib/rake/application.rb:160:in`standard_exception_handling'
/usr/lib/ruby/gems/1.8/gems/rake-10.0.4/lib/rake/application.rb:70:in `run'
/usr/lib/ruby/gems/1.8/gems/rake-10.0.4/bin/rake:33
/usr/bin/rake:23:in`load'
/usr/bin/rake:23
Tasks: TOP => redmine:plugins:migrate
jyjiang@swdev:/usr/share/redmine/plugins$

**Comment by doublechiang** [comment]
Hello,

I installed another fresh copy of Ubuntu and bitnami and install the plugin, this fresh copy works fine.
So I moved back to my "production' copy. This is my group working database with 500MB sql data and I should keep it in pretty safe place.

I found on the failed database, the project table do not have 'hipchat_auth_token', hipchat_room_name', and 'hipchat_notify' column.

While the new fresh installed system, the project table contain these column, do anyone have any idea?

Thanks in advance.

**Comment by doublechiang** [comment]
I think I found some hint why my working system can not install this plugin.
On the plugin installed successful system, executing migration command will generate table and has following logs.

==  AddHipChatTokenAndRoomIdToProject: migrating ==============================
-- add_column(:projects, :hipchat_auth_token, :string, {:default=>"", :null=>false})
   -> 0.0416s
-- add_column(:projects, :hipchat_room_name, :string, {:default=>"", :null=>false})
   -> 0.0090s
-- add_column(:projects, :hipchat_notify, :boolean, {:default=>false, :null=>false})
   -> 0.0169s
==  AddHipChatTokenAndRoomIdToProject: migrated (0.0694s) =====================

but on install failed system, no log and no table were generated.
I will keep on tracing why the migration command is not working.....

**Comment by doublechiang** [comment]
I have a work around now.
I went to database, create the column manually, then the plugin is work.
I don't know why running db:migration will not create the field anyway.
