### ISSUE TITLE
404 Not Found when trying to open configuration page

### ISSUE THREAD

**Issue by pengux** [hipchat/redmine_hipchat#20]
Environment:
  Redmine version                2.5.0.stable
  Ruby version                   1.9.3-p484 (2013-11-22) [x86_64-linux]
  Rails version                  3.2.17
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.6.17
  Cvs                            1.12.13
  Bazaar                         2.5.1
  Git                            1.7.9.5
  Filesystem  
Redmine plugins:
  file_servers                   0.0.1
  issuefy                        0.2.0
  line_numbers                   1.0.0
  recurring_tasks                1.3.0
  redmine_agile                  1.0.1-light1.0.1
  redmine_announcements          1.0
  redmine_charts2                0.2.1
  redmine_code_review            0.6.3
  redmine_dashboard              2.2
  redmine_didyoumean             1.2.0
  redmine_embedded_video         0.0.3.1
  redmine_favorite_projects      1.0.1
  redmine_gist                   0.1.0
  redmine_gitlab_merge_request   0.0.3
  redmine_hipchat                2.0.0
  redmine_issue_checklist        2.0.5
  redmine_people                 0.1.6
  redmine_screenshot_paste       2.1.0
  redmine_tags                   2.1.0
  redmine_tweaks                 0.4.5
  redshares                      1.0.0

**Comment by vizh** [comment]
```
NoMethodError (undefined method `hipchat_auth_token' for #<Project:0xb404d6d4>):
  lib/redmine/hook.rb:61:in `send'
  lib/redmine/hook.rb:61:in `call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:153:in `call_hook'
  app/controllers/issues_controller.rb:479:in `save_issue_with_child_records'
  app/controllers/issues_controller.rb:466:in `save_issue_with_child_records'
  app/controllers/issues_controller.rb:188:in `update'
```

```
ActionView::Template::Error (undefined method `hipchat_auth_token' for #<Project:0xb404e23c>):
    1: <p>
    2:   <%= form.text_field :hipchat_auth_token %>
    3:   A token from <a href="https://www.hipchat.com/group_admin/api" target="_blank">your API tokens page</a>. Leave empty to use <%= link_to 'global settings', plugin_settings_path(:redmine_hipchat) %>.
    4: </p>
    5: 
  lib/redmine/views/labelled_form_builder.rb:31:in `text_field'
  lib/redmine/hook.rb:111:in `send'
  lib/redmine/hook.rb:111:in `view_projects_form'
  lib/redmine/hook.rb:61:in `send'
  lib/redmine/hook.rb:61:in `call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `call_hook'
```

**Comment by meineerde** [comment]
You need to run the database migrations of the plugin, i.e. you need to run

```
rake redmine:plugins:migrate RAILS_ENV=production
```

in your Redmine directory.
